sudo: required

language: python

python:
#  - "2.7"
  - "3.7"
  - "3.6"

env:
    global:
        - GH_REF: github.com/samreay/ChainConsumer.git

dist: xenial
services:
  - xvfb

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
    - conda update -q conda
    - conda install python=$TRAVIS_PYTHON_VERSION pip requests conda-build anaconda-client setuptools
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
    - hash -r
    - pip install wheel twine
    - pip install .
    - pip install -r requirements.txt
    - conda install matplotlib==3.1.3
    - ulimit -s unlimited

script:
    - py.test --cov=chainconsumer -vv

after_success:
    - codecov
    - chmod u+x deploy.sh
    - ./deploy.sh
    - chmod +x conda/deploy_anaconda.sh

deploy:
  - provider: script
    script: ./conda/deploy_anaconda.sh
    skip_cleanup: true
    on:
      python: 3.7
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
  - provider: pypi
    user: "samreay"
    password:
      secure: "etRu952bkCozacIuC38kgsr5Ul05QG5lY1ESrC50El0fdQjimCeDqislB8buYyD+TeXfPY4jN10ApFfYzTJGfVFsM5NLE/T6+UBfCx3h07jN5ewA9jY5LDKaP5UJ+e33NrC+vkvsxoB5BJzwtbmrj6TDM9/s8RxsIZYFpZ+PoJxO/S7g2d6g1kCkbG2Q/2PpWa4VRacS29CAlBkeDY6z7ZCLEnpK0733ccQPxNfbdmAsXdHnk1cLWA5FNzbp5Vjti/tet6Wv8aVgw1RgSSN3HQ/5hl/uDgmGlloHvXDAK7xdtEo0R5y9mR4cfVJOxARweLBS84bPEysI+N7VoOAQkrBRxL85YHtuFBBiQdGMQazG8M/FhO0aeyMj1KJM1yaLj8lQJN+9qeIrtagV1LkAW9kzWvE4NOCPah4LGy2NvgJ0L7F8Kmgk2ReAZ3FfbfGyoISg/iqGBwDTjYH0GtXc3DYswpKylkpdpkcCh13usyVYxoHUJ+pT594vNJrNk6qQof6PVUiBldXkoWofoJGgASUh6r1gbcK/qlgD+sOCRyQ7zH5N8H/0ecnEC+io178r/5NioVfmsNBS4izJQPVzdUb3bB3jDjMwOU+yO/amD0V9Te9ctqDJL8cWmBwj0UsKunpZ2qbWfPUwtNS9/ehHH8RElJv8IKuj+j/md91KQy0="
    skip_cleanup: true
    edge:
      branch: v1.8.45
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
      python: 3.7
  - provider: releases
    api_key: "${GITHUB_API_KEY2}"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
      python: 3.7
