sudo: required

language: python

python:
  - "2.7"
  - "3.6"

env:
    global:
        - GH_REF: github.com/samreay/ChainConsumer.git

install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
    - hash -r
    - pip install -r requirements.txt
    - ulimit -s unlimited

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - python setup.py clean install
    - py.test --cov=chainconsumer -v

after_success:
    - codecov
    - chmod u+x deploy.sh
    - ./deploy.sh
