sudo: required

language: python

python:
  - "2.7"
  - "3.6"

env:
    global:
        - GH_REF: github.com/samreay/ChainConsumer.git

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
    - conda update -q conda
    - conda install python=$TRAVIS_PYTHON_VERSION pip requests conda-build anaconda-client setuptools
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
    - hash -r
    - pip install wheel twine
    - pip install -r requirements.txt
    - ulimit -s unlimited

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - python setup.py clean install
    - py.test --cov=chainconsumer -vv

after_success:
    - codecov
    - chmod u+x deploy.sh
    - ./deploy.sh
    - chmod +x conda/deploy_anaconda.sh

deploy:
  - provider: script
    script: ./conda/deploy_anaconda.sh
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
  - provider: pypi
    user: "samreay"
    password:
      secure: "kvqxckhEA1gYXP028bywKqvmFsNDvaj5/34Tp5SXUM4cUPNti8AlJijDS2GRLfA+sPVgHMsAx47rX9AFWCSIMQi1P/Ahxxupk1Es4rsihjsfyOCi4rGgcLp9gx32Dnz8kKw4Sm5jJcqpz9mxD/YzaWGaJpaxCrTuxKOfEgdj2olAHZjApr+R5Ds7xD8tjO3qdFUE2JvmwboNJR6GCV5smUBM5ytdiDGYza/7SgBjtTPm4PPrd6htythFpg5P71iknJdZ7h61+amH2ksAOHEa5F1l5h5KagTuqnjhv4rXdKEYStPIoul/7T3nq8xEJ1psNHe9u5M25AZZnP5INXVa78BKFTe3NBCrC7R2xPKUncW08rl3pKtnMP5JpbGa0VT09aKSGScPSVrsNtHFyTu58WOiiMa/NM910Xb/yJ1KNprttk0nrUahC8cVVA6TAC9SeM/yHCEvoc83POgHOU5lm5GmXZKzj4JO6mRlLP8aR0Np4DwaPXGV+Tkz3FNrcRVxZv+iQvDGwjVZfgRdUJWbZLCodgOKpqFv3OacyP0OdD1MB/OycuvlfkE44tEgF5JrWhb3LtfJcugOGH+SvxM8yHFE/clHOJ7LIfmGXEeUCWbCIpxkzTo5he7G7IIstpmlRsjd/7n60uLt2Uk7SgQ7KdKDEECsmbpJ3LpmxKtnA8c="
    skip_cleanup: true
    edge:
      branch: v1.8.45
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
      python: 3.6
  - provider: releases
    api_key: "${GITHUB_API_KEY2}"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9,\.]*$
      python: 3.6
