sudo: required

language: c

env:
    global:
        - GH_REF: github.com/samreay/ChainConsumer.git

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.5

        - os: linux
          env: PYTHON_VERSION=2.7

install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - sudo apt-get install dvipng
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create --yes -n test python=$PYTHON_VERSION setuptools pip pytest pytest-cov
    - source activate test
    - pip install --only-binary=numpy,scipy,matplotlib numpy scipy matplotlib
    - pip install sphinx numpydoc sphinx_rtd_theme Pillow sphinx_gallery codecov
    - pip install -r requirements.txt
    - ulimit -s unlimited

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 5

script:
    - python setup.py clean install
    - py.test --cov=chainconsumer -v

after_success:
    - codecov
    - chmod u+x deploy.sh
    - ./deploy.sh
