site_name: ChainConsumer
site_url: https://samreay.github.io/chainconsumer/
site_author: Samuel Hinton

edit_uri: ""
repo_name: samreay/chainconsumer
repo_url: https://github.com/samreay/chainconsumer

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - search.tabs.link
    - navigation.expand
    - toc.follow
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

plugins:
  autorefs: {}
  mkdocstrings:
    handlers:
      python:
        paths: [.]
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.pydantic.dev/latest/objects.inv
        options:
          members_order: source
          separate_signature: true
          filters: ["!^_"]
          show_root_heading: true
          show_if_no_docstring: true
          show_signature_annotations: true
  gallery:
    examples_dirs: docs/examples          # path to your example scripts
    gallery_dirs: docs/generated/gallery  # where to save generated gallery
    image_srcset: ['2x']
    within_subsection_order: FileNameSortKey
  search: {}

markdown_extensions:
  - mdx_include:
      base_path: docs
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences

watch:
  - docs
  - src
nav:
  - Home: index.md
  - Usage: usage.md
  - Python API:
      - ChainConsumer: api/consumer.md
      - Chain: api/chain.md
      - ChainConfig: api/chainconfig.md
      - Plotter: api/plotter.md
      - PlotConfig: api/plotconfig.md
      - Truth: api/truth.md
  - Examples: generated/gallery
