
package:
  name: 'chainconsumer'
  version: "{{ environ['VERSION'] }}"

source:
  git_url: https://github.com/samreay/chainconsumer.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  script_env:
    - VERSION
    - CONDA_BLD_PATH
     
requirements:
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib >1.6.0,<2.1.0
    - statsmodels >=0.7.0
  run:
    - python
    - numpy
    - scipy
    - matplotlib >1.6.0,<2.1.0
    - statsmodels >=0.7.0


about:
  home: http://github.com/samreay/ChainConsumer
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Consume chains and produce plots and tables
  description: 'Package documentation: http://samreay.github.io/ChainConsumer'
  doc_url: 'https://samreay.github.io/ChainConsumer/'
  dev_url: 'http://github.com/samreay/ChainConsumer'

